---
branches: 
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "develop"
    prerelease: true
  - name: "staging"
    prerelease: true
  - name: "devops"
    prerelease: true
preset: "angular"
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo v${nextRelease.version} > VERSION.txt"